---
title: "STAS plotting"
author: "Colin Bailey"
date: "2024-11-01"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)

STAS <- read.csv("Data_in\\STAS.csv")

STAS %>% filter(brood_year >= 1985) %>% 
  ggplot(aes(x = brood_year, y = stas*100))+
  geom_line()+
  theme_classic()+
  labs(x = "Brood year", y = "Smolt-to-adult survival (%)")+
  geom_hline(yintercept = 6.3, linetype = "dashed", size = 0.8, colour = "#01665e")+
  geom_hline(yintercept = 1.5, linetype = "dashed", size = 0.8, colour = "#d01c8b")+
  theme(axis.text = element_text(size = 10), axis.title = element_text(size = 9))

ggsave("STAS_plot.png", units = "in", height = 4, width = 6, dpi = 500)
```



```{r CU 4 panels}
dat <- readRDS("~/DATA/1975-2023 IFR COHO_ESC_MASTER_Full.rds")

cu_esc <- dat %>% filter(WSP.2014.Data.Use.Categories != "not used" & ReturnYear %in% c(1984:2022)) %>% 
  group_by(ReturnYear, ConservationUnit) %>% 
  summarize(esc = sum(Natural.Returns, na.rm = T),
            rec = sum(prefishery.return.natural, na.rm = T))

cu_esc %>% filter(ReturnYear %in% c(1984:2022)) %>% ggplot(aes(x = ReturnYear, y = esc))+
  geom_line()+
  facet_wrap(.~ ConservationUnit)+
  theme_classic()

cu_esc %>% filter(ReturnYear %in% c(1984:2022)) %>% ggplot(aes(x = ReturnYear, y = rec))+
  geom_line()+
  facet_wrap(.~ ConservationUnit)+
  theme_classic()

cu_esc %>% filter(ReturnYear %in% c(1984:2022)) %>% ggplot(aes(x = ReturnYear, y = catch))+
  geom_line()+
  facet_wrap(.~ ConservationUnit)+
  theme_classic()

```
